language: minimal

services:
  - docker

branches:
  except:
    - gh-pages
install:
  - docker pull jjmerelo/test-perl6
  - docker images

script: docker run -t  -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6
